-- Run as main.lua in a LÖVE runner containing the checkout's other files.
require 'loxel'
require 'funkin'

local function checkError(fn, message)
 local ok, err = pcall(fn)
 assert(not ok and tostring(err):find(message, 1, true), tostring(err))
end

function love.load()
 local ok, err = xpcall(function()
  love.window.setMode(320,240,{vsync=0})
  game.width, game.height=320,240
  assert(love.filesystem.getInfo('funkin/backend/scripts/compat.lua'), 'missing opt-in Lua compatibility module')
  local Compat = require 'funkin.backend.scripts.compat'
  love.filesystem.createDirectory('assets/images')
  local image=love.image.newImageData(8,4); image:encode('png','assets/images/test-compat-atlas.png'); image:release()
  love.filesystem.write('assets/images/test-compat-atlas.xml','<TextureAtlas imagePath="test-compat-atlas.png"><SubTexture name="idle0000" x="0" y="0" width="4" height="4"/><SubTexture name="idle0001" x="4" y="0" width="4" height="4"/></TextureAtlas>')
  local state = Group()
  state.camHUD, state.camOther, state.camNotes = Camera(), Camera(), Camera()
  game.camera=Camera()
  state.boyfriend = Sprite(10, 20)
  state.notes = Group(); state.notes:add({x=3}); state.flag=false
  local Gamestate=require 'loxel.lib.gamestate'; Gamestate.stack[1]=state
  local script = Script('tests/engine/compat-fixture.lua', false, true, true)
  assert(not script.closed and script.chunk, 'real native Script failed to load')
  local ctx = Compat.new(state, script)
  local f = script.variables
  f.setProperty('camGame.zoom',1.25); f.setProperty('camHUD.alpha',.5)
  assert(game.camera.zoom==1.25 and state.camHUD.alpha==.5 and state.camNotes.alpha==1)
  assert(f.getProperty('boyfriend.x')==10 and f.getProperty('flag')==false)
  f.setProperty('boyfriend.scale.x', 2)
  f.setProperty('notes.members[0].x', 8)
  assert(state.boyfriend.scale.x==2 and f.getPropertyFromGroup('notes',0,'x')==8)
  f.setPropertyFromGroup('notes',0,'x',9)
  assert(f.getProperty('notes.members.0.x')==9)
  checkError(function() f.setProperty('notes.members[9].x',2) end,'missing')
  checkError(function() f.getProperty('boyfriend..x') end,'path')
  checkError(function() f.runHaxeCode('trace(1)') end,'unsupported')
  f.makeLuaSprite('panel',nil,30,40); f.makeGraphic('panel',32,16,'FF8000')
  f.addLuaSprite('panel',true); f.setObjectCamera('panel','hud')
  local panel=ctx.objects.panel
  assert(panel.width==32 and panel.height==16 and panel.cameras[1]==state.camHUD)
  assert(f.getObjectOrder('panel')==0)
  f.makeLuaSprite('back',nil,0,0); f.addLuaSprite('back',false)
  assert(state.members[1]==ctx.objects.back)
  f.setObjectOrder('panel',0); assert(state.members[1]==panel)
  f.scaleObject('panel',2,3); f.setScrollFactor('panel',0,0)
  assert(panel.width==64 and panel.height==48 and panel.scrollFactor.x==0)
  f.makeAnimatedLuaSprite('actor','test-compat-atlas',0,0)
  f.addAnimationByPrefix('actor','idle','idle',12,true)
  f.addAnimationByIndices('actor','once','idle','0,1',24,false)
  f.addOffset('actor','idle',3,4); f.playAnim('actor','idle',true)
  assert(ctx.objects.actor.animation.curAnim.framerate==12)
  assert(ctx.objects.actor.animation.curAnim.offset.x==3)
  ctx.objects.actor:update(.1)
  assert(ctx.objects.actor.animation.curAnim.frame>1)
  f.doTweenX('move','panel',130,.25,'quadInOut')
  f.runTimer('tick',.1,2)
  ctx:update(.1); assert(panel.x>30 and panel.x<130)
  ctx:update(.1); ctx:update(.1)
  assert(panel.x==130 and f.tweenTag=='move' and f.timerCount==2 and f.timerLeft==0)
  f.doTweenZoom('cameraZoom','camGame',2,.1,'circIn')
  ctx:update(2)
  assert(game.camera.zoom==2,'slow frame circular easing did not reach finite target')
  f.runTimer('cancel',.1,1); f.cancelTimer('cancel')
  f.doTweenY('cancel','panel',100,.1); f.cancelTween('cancel')
  ctx:update(.2); assert(panel.y==40 and f.timerTag=='tick')
  ctx:forward('create'); ctx:forward('postCreate'); ctx:forward('step',16); ctx:forward('beat',4)
  ctx:forward('event',{e='Flash',v={'yes','no'}}); ctx:forward('postUpdate',.1)
  assert(f.created and f.postCreated and f.curStep==16 and f.curBeat==4 and f.eventName=='Flash')
  ctx.callbackNames.event='onCompatEvent'
  script:set('onCompatEvent',function(name,v1) script:set('renamedEvent',name); assert(v1=='scalar') end)
  script:set('onEvent',function(event) ctx:forward('event',event) end)
  script:call('onEvent',{e='Native',v='scalar'})
  assert(f.renamedEvent=='Native' and next(script.__failedfunc)==nil,'native event forwarding recursed')
  f.playSound('scrollMenu',.3,'tone')
  local source=ctx.sounds.tone._source
  assert(source and source:typeOf('Source') and ctx.sounds.tone.volume==.3)
  f.setSoundVolume('tone',.2); f.pauseSound('tone'); f.resumeSound('tone')
  f.playMusic('freakyMenu',.2,true)
  assert(ctx.sounds.__music and game.sound.music==nil,'compat music replaced native song music')
  local musicSource=ctx.sounds.__music._source
  local cachedMusic=paths.getMusic('freakyMenu')
  assert(musicSource~=cachedMusic,'compat borrowed cached stream Source')
  local peerScript=Script('tests/engine/compat-fixture.lua',false,true,true)
  local peer=Compat.new(state,peerScript)
  peerScript.variables.makeLuaSprite('panel',nil,1,2)
  peerScript.variables.addLuaSprite('panel',true)
  peerScript.variables.runTimer('tick',1,0)
  local closedListener=false
  peerScript.closeCallback:add(function() closedListener=true end)
  peerScript:close()
  assert(closedListener,'compat close cleanup skipped another native close listener')
  assert(peer.disposed and ctx.objects.panel==panel and #state.members==2,'script close broke scoped tag ownership')
  f.runTimer('orphan',1,0); f.doTweenX('orphan','panel',100,1)
  local makeSprite=f.makeLuaSprite
  ctx:dispose(); ctx:dispose()
  assert(#state.members==0 and #ctx.timer.instances==0 and #ctx.tween.instances==0)
  assert(not pcall(source.isPlaying,source),'owned Source remained live after dispose')
  assert(not pcall(musicSource.isPlaying,musicSource),'owned stream Source remained live after dispose')
  assert(pcall(cachedMusic.isPlaying,cachedMusic),'disposing stream released cached Source')
  checkError(function() makeSprite('late') end,'disposed')
  assert(rawget(script.variables,'getProperty')==nil,'injected API not restored')
  local untouched = Script('tests/engine/compat-fixture.lua',false,true,true)
  assert(rawget(untouched.variables,'getProperty')==nil,'compat API leaked to native script')
  untouched:call('native',5); assert(untouched.variables.nativeValue==5)
  local during=Compat.new(state,untouched)
  untouched:set('onTimerCompleted',function() during:dispose() end)
  untouched.variables.runTimer('first',.1,1); untouched.variables.runTimer('last',.1,1)
  during:update(.2)
  assert(during.disposed,'timer completion did not dispose context')
  -- A real native script opts in via the engine factory and forwards its callbacks.
  local example=Script('examples/compat-mod/data/scripts/compat-demo.lua',false,true,true)
  assert(not example.closed and example.chunk,'example failed to load')
  example:call('create'); example:call('update',.6); example:call('postUpdate',.6)
  example:call('step',8); example:call('beat',2); example:call('leave')
  assert(next(example.__failedfunc)==nil,'example callback failed')
  script:close(); untouched:close(); example:close()
  print('COMPAT PASS: real Script, property arrays, Sprite/animation, scoped Timer/Tween, tagged Source, disposal, native isolation, example')
 end,debug.traceback)
 if not ok then print('COMPAT FAIL: '..err) end
 love.event.quit(ok and 0 or 1)
end
function love.update() end
function love.draw() end
function love.quit() end
function love.errorhandler(err) print(err); return function() return 1 end end
